server:
  port: 8888
  servlet:
    context-path: /au-api
logging:
  level:
    com.lazycece.au: debug
au:
  enable: true
  api:
    token:
      enable: true
      secret: 75HVYG0VQVDEYPLLODZUX99ZCV333EKY
#      header: AU-API-TOKEN-HEADER
#      issuer: AU-API
#      expire: 30m
#      refresh: true
      include-patterns: /**
      exclude-patterns: /u/login
    param:
      enable: true
      secret: 75HVYG0VQVDEYPLLODZUX99ZCV333EKY
#      crypto-type: des3
      param-clazz: com.lazycece.au.api.spring.boot.sample.entity.dos.ApiParams
#      time-interval: 3m
#      include-patterns: /**
#      exclude-patterns:
