server:
  port: 8888
  servlet:
    context-path: /au-api
au:
  enable: true
  api:
    token:
      enable: true
      secret: 75HVYG0VQVDEYPLLODZUX99ZCV333EKY
      header: AU-API-TOKEN-HEADER
      issuer: AU-API
      expire: 30m
      refresh: true
      exclude-patterns: /**
      include-patterns: /u/login
    param:
      enable: true
      secret: 75HVYG0VQVDEYPLLODZUX99ZCV333EKY
      crypto-type: des3
      param-clazz: com.lazycece.au.api.spring.boot.sample.entity.dos.ApiParams
      time-interval: 2m
      include-patterns: /**
      exclude-patterns:
